name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'Demo'
          destination_repo: 'arpit1503khanna/target-repository'
          destination_folder: '.'
          user_email: 'arpit.khanna@sourcefuse.com'
          user_name: 'Arpit'
          commit_message: ${{ github.event.head_commit.message }}
